name: Security

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every Monday at 9am UTC
    - cron: '0 9 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit[toml] safety pip-audit
        pip install -e .
    
    - name: Run Bandit security scan
      run: |
        bandit -r claude_code_indexer/ -f json -o bandit-report.json || true
        bandit -r claude_code_indexer/ -f txt || true
      continue-on-error: true
    
    - name: Upload Bandit results
      uses: actions/upload-artifact@v4
      with:
        name: bandit-results
        path: bandit-report.json
      if: always()
    
    - name: Check dependencies with Safety
      run: |
        safety check --json --output safety-report.json || true
        safety check || true
      continue-on-error: true
    
    - name: Upload Safety results
      uses: actions/upload-artifact@v4
      with:
        name: safety-results
        path: safety-report.json
      if: always()
    
    - name: Run pip-audit
      run: |
        pip-audit --desc --format json --output pip-audit-report.json || true
        pip-audit --desc || true
      continue-on-error: true
    
    - name: Upload pip-audit results
      uses: actions/upload-artifact@v4
      with:
        name: pip-audit-results
        path: pip-audit-report.json
      if: always()
    
    - name: Check for secrets with TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --debug --only-verified

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python
        queries: security-and-quality

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3